version: 2

jobs:
  build:
    working_directory: ~/
    
    docker:
      - image: quartic/uber-builder:117

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build Docker image
          command: docker build -t backer-upper .

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: |
            docker tag backer-upper ${GCLOUD_DOCKER_REPOSITORY}/backer-upper:${CIRCLE_BUILD_NUM}
            docker push ${GCLOUD_DOCKER_REPOSITORY}/backer-upper:${CIRCLE_BUILD_NUM}
