version: 2

jobs:
  build:
    working_directory: ~/backer-upper
    
    docker:
      - image: ${GOOGLE_DOCKER_REPOSITORY}/uber-builder:139
        auth: { username: _json_key, password: "${GOOGLE_CREDENTIALS}" }

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build Docker image
          command: docker build -t backer-upper .

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: docker-tag-and-push backer-upper ${CIRCLE_BUILD_NUM}
